name: Plugins - CI (Push)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout Plugins
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain

      - name: Building plugins
        run: ./gradlew build

  bootstrap:
    runs-on: ubuntu-latest
    needs: [build]
    name: Bootstrap

    permissions:
      actions: write
      contents: write
      repository-projects: write

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4

      - name: Checkout Release Repo
        uses: actions/checkout@v4
        with:
          repository: OreoCupcakes/kotori-plugins-releases
          ref: master
          persist-credentials: false
          fetch-depth: 0
          path: kotori-plugins-releases

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain

      - name: Building plugins
        run: ./gradlew build

      - name: Bootstrapping plugins
        run: ./gradlew bootstrapPlugins

      - name: Copy bootstrap
        run: cp -af /home/runner/work/kotori-plugins/kotori-plugins/bootstrap/. /home/runner/work/kotori-plugins/kotori-plugins/kotori-plugins-releases

      - name: Copy Info
        run: cp -af /home/runner/work/kotori-plugins/kotori-plugins/info.json /home/runner/work/kotori-plugins/kotori-plugins/kotori-plugins-releases

      - name: Copy Hooks
        run: cp -af /home/runner/work/kotori-plugins/kotori-plugins/hooks.json /home/runner/work/kotori-plugins/kotori-plugins/kotori-plugins-releases

      - name: Commit bootstrap
        run: |
          git add $(git ls-files -o --exclude-standard) *.json
          git diff-index --quiet HEAD \
          || git -c user.name="GitHub" -c user.email="noreply@github.com" commit \
            --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
            -m "Automatic plugin bootstrap"
        working-directory: /home/runner/work/kotori-plugins/kotori-plugins/kotori-plugins-releases

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: /home/runner/work/kotori-plugins/kotori-plugins/kotori-plugins-releases
          repository: OreoCupcakes/kotori-plugins-releases
          github_token: ${{secrets.KOTORI}}